version: '3'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=abc
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=e843lnasxax9JZxzkjnW
    ports:
      - 5432
    volumes:
      - abc_postgres:/var/lib/postgresql:rw
      - ./schemas/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - abc

  redis:
    image: redis:latest
    ports:
      - 6379
    restart: unless-stopped
    command: redis-server --requirepass ""
    volumes:
      - abc_redis:/var/lib/redis:rw
    networks:
      - abc

volumes:
  abc_redis:
  abc_postgres:

networks:
  abc:
    external: True